#!/bin/bash

bspc config border_width          0
bspc config focused_border_color  #000000
bspc config window_gap            16
bspc config focus_follows_pointer true

bspc config top_padding 26
bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc monitor -d 1 2 3 4 5
bspc desktop ^2 -l monocle

bspc rule -a Firefox desktop=^2
bspc rule -a Lxappearance state=floating center=true
bspc rule -a Nitrogen state=floating center=true
bspc rule -a mpv state=floating center=true
bspc rule -a pavucontrol state=floating

xset -dpms && xset s off
nitrogen --restore
[ ! -s ~/.config/mpd/pid ] && mpd
xsetroot -cursor_name left_ptr
panel &
dunst &
