#!/bin/sh

PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=25
PANEL_FONT="Hack:size=9"
PANEL_FONT_ICON="icomoon:size=9"
PANEL_WM_NAME=bspwm_panel

if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

echo $$ > /tmp/panel-pid

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc subscribe report > "$PANEL_FIFO" &


# title
xtitle -sf 'T%s' > "$PANEL_FIFO" &

# applauncher icon
echo -e 'L\ue9bb' > $PANEL_FIFO &

# clock
while true; do
              echo -e 'C\ue94e' $(date +'%I:%M:%S %p')
            sleep 1
done > "$PANEL_FIFO" &

# date
while true; do
              echo -e 'D\ue953' $(date +'%a. %d/%m')
            sleep 1
done > "$PANEL_FIFO" &

. panel_colors


panel_bar < "$PANEL_FIFO" | lemonbar -a 32 -n "$PANEL_WM_NAME" -g 1904x$PANEL_HEIGHT+8+2 -f "$PANEL_FONT" -f "$PANEL_FONT_ICON" -F "$COLOR_DEFAULT_FG" -B "$COLOR_DEFAULT_BG" | sh &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
	tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
